package OrbChat;

/**
* OrbChat/ChatServerIntHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OrbChat.idl
* Sunday, May 29, 2016 2:41:30 PM SGT
*/

public final class ChatServerIntHolder implements org.omg.CORBA.portable.Streamable
{
  public OrbChat.ChatServerInt value = null;

  public ChatServerIntHolder ()
  {
  }

  public ChatServerIntHolder (OrbChat.ChatServerInt initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = OrbChat.ChatServerIntHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    OrbChat.ChatServerIntHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return OrbChat.ChatServerIntHelper.type ();
  }

}
