package OrbChat;


/**
* OrbChat/ChatClientIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OrbChat.idl
* Sunday, May 29, 2016 2:41:30 PM SGT
*/

public interface ChatClientIntOperations 
{
  void tell (String name);
  String getName ();
} // interface ChatClientIntOperations
