package OrbChat;


/**
* OrbChat/ChatClientIntPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OrbChat.idl
* Sunday, May 29, 2016 2:41:30 PM SGT
*/

public abstract class ChatClientIntPOA extends org.omg.PortableServer.Servant
 implements OrbChat.ChatClientIntOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("tell", new java.lang.Integer (0));
    _methods.put ("getName", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // OrbChat/ChatClientInt/tell
       {
         String name = in.read_string ();
         this.tell (name);
         out = $rh.createReply();
         break;
       }

       case 1:  // OrbChat/ChatClientInt/getName
       {
         String $result = null;
         $result = this.getName ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:OrbChat/ChatClientInt:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ChatClientInt _this() 
  {
    return ChatClientIntHelper.narrow(
    super._this_object());
  }

  public ChatClientInt _this(org.omg.CORBA.ORB orb) 
  {
    return ChatClientIntHelper.narrow(
    super._this_object(orb));
  }


} // class ChatClientIntPOA
