package OrbChat;


/**
* OrbChat/ChatServerIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OrbChat.idl
* Sunday, May 29, 2016 2:41:30 PM SGT
*/

public interface ChatServerIntOperations 
{
  boolean login (OrbChat.ChatClientInt a);
  void publish (String s);
  String getConnected ();
  void getConnected (String newGetConnected);
} // interface ChatServerIntOperations
