package OrbChat;


/**
* OrbChat/ChatServerIntHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OrbChat.idl
* Sunday, May 29, 2016 2:41:30 PM SGT
*/

abstract public class ChatServerIntHelper
{
  private static String  _id = "IDL:OrbChat/ChatServerInt:1.0";

  public static void insert (org.omg.CORBA.Any a, OrbChat.ChatServerInt that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static OrbChat.ChatServerInt extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (OrbChat.ChatServerIntHelper.id (), "ChatServerInt");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static OrbChat.ChatServerInt read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ChatServerIntStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, OrbChat.ChatServerInt value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static OrbChat.ChatServerInt narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof OrbChat.ChatServerInt)
      return (OrbChat.ChatServerInt)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      OrbChat._ChatServerIntStub stub = new OrbChat._ChatServerIntStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static OrbChat.ChatServerInt unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof OrbChat.ChatServerInt)
      return (OrbChat.ChatServerInt)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      OrbChat._ChatServerIntStub stub = new OrbChat._ChatServerIntStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
